'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace ServiceReference1
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference1.WebService1Soap")>  _
    Public Interface WebService1Soap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/listarEmpresas", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function listarEmpresas() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/listarEmpresas", ReplyAction:="*")>  _
        Function listarEmpresasAsync() As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/buscarEmpresa", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function buscarEmpresa(ByVal RUC As String) As String()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/buscarEmpresa", ReplyAction:="*")>  _
        Function buscarEmpresaAsync(ByVal RUC As String) As System.Threading.Tasks.Task(Of String())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/obtenerDatosEmpresa", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function obtenerDatosEmpresa(ByVal RUC As String) As String()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/obtenerDatosEmpresa", ReplyAction:="*")>  _
        Function obtenerDatosEmpresaAsync(ByVal RUC As String) As System.Threading.Tasks.Task(Of String())
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface WebService1SoapChannel
        Inherits ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WebService1SoapClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.WebService1Soap)
        Implements ServiceReference1.WebService1Soap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function listarEmpresas() As System.Data.DataSet Implements ServiceReference1.WebService1Soap.listarEmpresas
            Return MyBase.Channel.listarEmpresas
        End Function
        
        Public Function listarEmpresasAsync() As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements ServiceReference1.WebService1Soap.listarEmpresasAsync
            Return MyBase.Channel.listarEmpresasAsync
        End Function
        
        Public Function buscarEmpresa(ByVal RUC As String) As String() Implements ServiceReference1.WebService1Soap.buscarEmpresa
            Return MyBase.Channel.buscarEmpresa(RUC)
        End Function
        
        Public Function buscarEmpresaAsync(ByVal RUC As String) As System.Threading.Tasks.Task(Of String()) Implements ServiceReference1.WebService1Soap.buscarEmpresaAsync
            Return MyBase.Channel.buscarEmpresaAsync(RUC)
        End Function
        
        Public Function obtenerDatosEmpresa(ByVal RUC As String) As String() Implements ServiceReference1.WebService1Soap.obtenerDatosEmpresa
            Return MyBase.Channel.obtenerDatosEmpresa(RUC)
        End Function
        
        Public Function obtenerDatosEmpresaAsync(ByVal RUC As String) As System.Threading.Tasks.Task(Of String()) Implements ServiceReference1.WebService1Soap.obtenerDatosEmpresaAsync
            Return MyBase.Channel.obtenerDatosEmpresaAsync(RUC)
        End Function
    End Class
End Namespace
